name: style_advisor
description: A new Flutter project for Style Advisor.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  dio: ^5.4.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.12.0
  glow_bottom_app_bar: ^1.5.2
  flutter_card_swiper: ^7.2.0
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  image: ^4.7.2
  camera: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/wardrobe/
    - assets/images/wardrobe/wbottom/
    - assets/images/wardrobe/wtop/
    - assets/images/wardrobe/bodycon/
    - assets/images/wardrobe/jacket/
    - assets/icons/
